### ISSUE TITLE
It crashes if you use binaries

### ISSUE THREAD

**Issue by georgij** [Adyen/adyen-checkout-android#14]
`D/Error: ERR: stack=java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/volley/toolbox/JsonObjectRequest;
                                                                              at adyen.com.adyenpaysdk.services.PaymentServiceImpl.fetchPublicKey(PaymentServiceImpl.java:29)
                                                                              at adyen.com.adyenpaysdk.Adyen.fetchPublicKey(Adyen.java:53)
                                                                              at adyen.com.adyenuisdk.PaymentActivity$2.onClick(PaymentActivity.java:212)
                                                                              at android.view.View.performClick(View.java:4780)
                                                                              at android.view.View$PerformClick.run(View.java:19866)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.volley.toolbox.JsonObjectRequest"`

**Comment by mickyzinho** [comment]
Having the same problem. Happens after clicking on the "Pay..." button.

**Comment by georgij** [comment]
Can be fixed by adding `compile 'com.android.volley:volley:1.0.0'` by the way.

**Comment by mickyzinho** [comment]
Yes, I did it the same way. That should be stated in the docs though. Also that you need the INTERNET permission.

**Comment by MerlinYu** [comment]
I think adyen document is so messy.
