### ISSUE TITLE
java.lang.NullPointerException: 

### ISSUE THREAD

**Issue by MerlinYu** [Adyen/adyen-checkout-android#21]
java.lang.NullPointerException: Attempt to invoke virtual method 'void adyen.com.adyenpaysdk.controllers.NetworkController.addToRequestQueue(com.android.volley.Request)' on a null object reference
	at adyen.com.adyenpaysdk.services.PaymentServiceImpl.fetchPublicKey(PaymentServiceImpl.java:51)
	at adyen.com.adyenpaysdk.Adyen.fetchPublicKey(Adyen.java:53)
	at co.cloudmall.android.payment.activity.AdyenActivityPresenter.adyenPay(AdyenActivityPresenter.java:61)
	at co.cloudmall.android.payment.activity.fragment.AdyenPayFragmentPresenter.adyenPay(AdyenPayFragmentPresenter.java:25)
	at co.cloudmall.android.payment.activity.fragment.AdyenPayFragment$1.onClick(AdyenPayFragment.java:66)
	at android.view.View.performClick(View.java:5207)
	at android.view.View$PerformClick.run(View.java:21177)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5441)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by MerlinYu** [comment]
Adyen is so many problems !!!!
